### ISSUE TITLE
Can't update by Microsoftstore to v.0.27.0.0!

### ISSUE THREAD

**Issue by RudeTheJack** [UWPX/UWPX-Client#136]

**Comment by COM8** [comment]
The MS Store is preventing me to upload the latest release to the store, size I had to change a part of the app identity to fix the broken push channel.
https://twitter.com/UWPX_APP/status/1279076440017973255

During my trial and error runs for fixing the push channel I deleted the `Live SDK` integration.
I was hoping to get a new link, which is not broken.
Turns out, once you deleted it, you can not create a new one.
Thanks for now warning, when clicking this button...
https://twitter.com/UWPX_APP/status/1254786200134578178

MS support is also not helpful, since they either want money from me, so I even can start chatting with them about that, or redirect you to ask questions in the forum.

There the only suggestion is to **DELETE** UWPX from the store and start all over again.

This is no solution for me, since then everybody would have redownload the app...

**Comment by RudeTheJack** [comment]
OK, I will wait till you solve it💪

**Comment by COM8** [comment]
There is no way I can deliver push support without braking updates.
To deliver push support I **have to** change the app identity.
This results in a new app in the Microsoft Store.
People **have to** redownload the app.

So I decided to do the following:
* Do not offer push support for versions < v.1.0
* Once version v.1.0 has been released people have to redownload a new and stable version of the app

**Comment by RudeTheJack** [comment]
> There is no way I can deliver push support without braking updates.
> To deliver push support I **have to** change the app identity.
> This results in a new app in the Microsoft Store.
> People **have to** redownload the app.
> 
> So I decided to do the following:
> 
> * Do not offer push support for versions < v.1.0
> * Once version v.1.0 has been released people have to redownload a new and stable version of the app

That's OK!
