### ISSUE TITLE
[UI rewrite] Xamarin.Forms (including Linux & Gtk# support) port

### ISSUE THREAD

**Issue by StEvUgnIn** [UWPX/UWPX-Client#137]
I am proposing to port UWPX-Client to Xamarin Platform, so that we can add iOS, android, GNU/Linux support and macOS support (as preview through Gtk#, later using Xamarin.Mac).

**Comment by COM8** [comment]
In theory, this would be possible since UWPX is written rather flexible and replacing individual components (e.g. push, sockets, db, ...) for platform specific ones should be possible.

**But**, I do not have any experience with that and also I'd like to have a rather good working XMPP Client for one platform, before I start porting it to others as well.

Any thoughts about that?

**Comment by StEvUgnIn** [comment]
I think it would be wise to expect Microsoft might write a wrapper or a tool to port the project from UWP to Xamarin Forms
