### ISSUE TITLE
Unable to connect to conversations.im after upgrade to v.0.31

### ISSUE THREAD

**Issue by chfrank-cgn** [UWPX/UWPX-Client#152]
## Bevor you create a new issue:

```
- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)
 

## Current behavior:

After upgrade to the latest version, UWPX no longer accepts the root CA provided by conversations.im

## Expected behavior:

I'd expect TLS connection to conversations.im to succeed

## Minimal reproduction of the problem with instructions:

After the upgrade, one needs to re-enter the credentials, but the account won't connect:

Error code:  1 [SOCKET_ERROR]
Socket error code:  24 [CertificateUntrustedRoot]
Error message:  TLS upgrade failed after 68.5984 ms with: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. (Exception from HRESULT: 0x800B0109)

Certificate issuer is:
Issuer: C = DE, ST = Berlin, L = Berlin, O = Conversations, OU = Hosting, CN = Conversations CA

## Environment:

```
App Version(s): 
v.0.31.0.0 <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [X] 2004
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Thanks for reporting this.
To me this does not look like something I can actively fix since I'm using the default WinSSL certificate chain for UWPX without any changes. To further diagnose this I have a couple of questions:
* Did you change anything on your certificates in Windows?
* Are you able to connect with other clients (Gajim, etc.) from the **same** PC to `conversations.im`?
* Is the connection running through any kind of Proxy/VPN/... ?

I will try to create an account at `conversations.im` to further diagnose this my self.

In the meantime if you are sure, nobody is manipulating or intercepting your connection, you can disable this type of TLS cert. validation in the UWPX settings:

![tls](https://user-images.githubusercontent.com/11741404/113551388-d8fdc280-95f4-11eb-8e5f-601cfb7a978b.gif)

**Comment by chfrank-cgn** [comment]
Hi Fabian,

many thanks for your kind reply! Disabling the TSL verification solved the connection issue, I just missed the option in the setup - sorry!

To your questions:

  *   Did you change anything on your certificates in Windows?

      No

  *   Are you able to connect with other clients (Gajim, etc.) from the same PC to conversations.im?

      Yes, but only by disabling certificate validation

  *   Is the connection running through any kind of Proxy/VPN/... ?

      No, simple cable-based home internet connection

All the best:

Chris

________________________________________

**Comment by COM8** [comment]
![grafik](https://user-images.githubusercontent.com/11741404/121777984-12265600-cb95-11eb-973c-05a59ed8958a.png)
Sadly I can not reproduce this one.
Is it still not working for you?

**Comment by chfrank-cgn** [comment]
Hi Fabian,

it seems to be working fine now - thank you!

Cheers: Chris

________________________________________
