### ISSUE TITLE
Not receiving group messages 

### ISSUE THREAD

**Issue by jhubler99** [UWPX/UWPX-Client#174]
Hi, 

I have a Dell Inspiron 15 Inch 7591 2-in-1 laptop running Windows 10 Home. I bought a JMP number so I can text and make phone calls from my laptop. My JMP number is set up through movim.eu . Since I want push notifications when I receive a text message or an incoming phone call, I downloaded UWPX. It installed successfully. I connected the UWPX client to my Movim account. I can send and receive text messages through my client. However, I cannot receive group text messages in the UWPX client. On the other hand, I can send group text messages from the UWPX client successfully. I checked on my Movim account and can see the replies from my group. I would like to see the replies from my group in the UWPX client. Am I missing something? 

Thank you

**Comment by COM8** [comment]
This is a limitation of the specification for ([MUC](https://xmpp.org/extensions/xep-0045.html)) group chats and [push notifications](https://xmpp.org/extensions/xep-0357.html). There is simply no way (without completely running the app in the background all the time) so that UWPX can receive push notifications for group chats. For 1:1 chats, sure, but not for group chats.

And I can not let the app always run in the background since there are UWP (Windows) limitations that prevent this since the app initially was designed for Windows Phones, and now I would have to rewrite core parts to make this possible.

I'm sorry for this sad answer, and I suggest switching to Signal or Matrix if you want reliable push notifications for group chats. I'm also thinking about this step right now :)

**Comment by COM8** [comment]
But thank you for your request!

**Comment by jhubler99** [comment]
Hi, 

Thank you for your quick response. However, SMS is handled through Cheogram and JMP. As far as XMPP is concerned a "sms group chat" is just a really long single Jabber ID that it is communicating with. It never touches the MUC component of XMPP. For example if I want to send a group text message to three recipients, I would use: number1,number2,number3@cheogram.com. If I use this Jabber ID, I can send message through the UWPX client but not receive the messages. However, I can receive the messages on my Movim account. Is it possible that the UWPX client is silencing Jabber ID's that is not in my contact list? 

Thank you

**Comment by COM8** [comment]
OK, then this sounds like a bug. Could you please try the following:

* Go to `Settings` -> `Misc` and set the `Log-Level` to `Trace`
* Click on `Open app data folder (PC only)` and keep this window open
* Send chat messages to your account
* Upload the contents of you `Logs` directory here so a can work on a hotfix for this

**Comment by jhubler99** [comment]
Hi @COM8, 

Thank you for the information. I set the `Log-Level` to `Trace`. I texted a group of people so there should be a good log. Here is an overview with the time stamps that I sent/received messages: 

- **10:59** - Sent message to this Jabber ID (`number1,number2@cheogram.com`) via UWPX. 
- **11:03** - Received message in UWPX from one of the recipients.
- **11:05** - Received message in UWPX from the other recipient. 
- **11:08** - Received message in UWPX from one of the recipients.
- **11:14** - Sent message to this Jabber ID above. 
- **11:23** - Received message in UWPX from one of the recipients.
- **11:25** - Sent message to a different Jabber ID with same syntax (`number1,number2@cheogram.com`) except with different numbers via UWPX. 
- **11:28** - Received message in UWPX from one of the recipients from this current Jabber ID. 
- **12:00** - Received message in UWPX from original Jabber ID as per **10:59**
- **12:06** - Did NOT receive message in UWPX from one of the recipients. Received in Movim though. 
- **12:12** - Did NOT receive message in UWPX from a Jabber ID. Received in Movim though. 

Attached is the `Logs` directory. [UWPX Logs.zip](https://github.com/UWPX/UWPX-Client/files/8665392/UWPX.Logs.zip)
Thank you for looking into this!

**Comment by COM8** [comment]
I think this has something to do with [Message Carbons](https://xmpp.org/extensions/xep-0280.html) and [Push](https://xmpp.org/extensions/xep-0357.html).
UWPX is disconnected between 12:01:08 and 12:12:43. So your server (movim.eu) should send a carbon copy of your message to the UWPX push server, which then should forward it to the app and wake it up.

But when enabling push notifications the following happens:
```xml
// UWPX -> nl.movim.eu
<iq type="set" id="be3068a4-0ae5-4413-a671-d78f8ef05246">
  <enable jid="push@xmpp.uwpx.org" node="ZZZZ" xmlns="urn:xmpp:push:0">
    <x type="submit" xmlns:xdd="urn:xmpp:xdata:dynamic" xmlns="jabber:x:data">
      <field var="FORM_TYPE" type="hidden">
        <value>http://jabber.org/protocol/pubsub#publish-options</value>
      </field>
      <field var="secret" type="hidden">
        <value>YYYY</value>
      </field>
    </x>
  </enable>
</iq> 
```
```xml
<iq xml:lang='en' to='XXX@movim.eu/UWPX_404741658' from='XXX@movim.eu' type='error' id='be3068a4-0ae5-4413-a671-d78f8ef05246'>
    <enable node='ZZZZZ' jid='push@xmpp.uwpx.org'
        xmlns='urn:xmpp:push:0'>
        <x type='submit'
            xmlns='jabber:x:data'>
            <field var='FORM_TYPE' type='hidden'>
                <value>http://jabber.org/protocol/pubsub#publish-options</value>
            </field>
            <field var='secret' type='hidden'>
                <value>YYYYY</value>
            </field>
        </x>
    </enable>
    <error type='wait'>
        <internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
        <text xml:lang='en'
            xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Database failure</text>
    </error>
</iq>
```

Enabling push fails because `movim.eu` replies with: "Database failure".
I will try by my own over the weekend in case this also happens for me, I will try to get in touch with `movim.eu` to get it fixed for you.

**Comment by jhubler99** [comment]
Hi @COM8, 

Thank you for looking into this further. I appreciate it very much! 🙂

**Comment by COM8** [comment]
First, I can confirm this issue and I also can reproduce it with a 'movim.eu' account.
I talked to the server maintainer over at 'movim@conference.movim.eu' and it looks like a misconfiguration on their end. They let the server announce support for it, but then it's disabled internally somehow.

**Comment by jhubler99** [comment]
Hi @COM8, 

Thank you for the information. Why would they give their server support for push but then disable it?

**Comment by COM8** [comment]
Don't know. This is all I got as an explanation. I suggest switching servers for push: https://providers.xmpp.net/

**Comment by jhubler99** [comment]
Hi @COM8, 

Thank you for taking the time to look into this last weekend. Appreciate it! 👍
