### ISSUE TITLE
Report: Windows don't move, Enter to send, notification noise

### ISSUE THREAD

**Issue by Echolon** [UWPX/UWPX-Client#62]
- [X] I searched for similar issues and did not find one
- [X] My friend is use the developer mode to get it installed... actually I don't know what he did^^
**--> So I report from a friends experience!**

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)

## Problems:

- [X] Windows weren't able to move or replace
- [X] Enter to send is switched on - but doesn't work
- [X] If there is a window in the background notification sounds are not played and winodws do not blink orange.
- [X] Wishes: Install app not from Store only

If these problems are known, just close it please.

App Version(s): 
recent github = "Weiß nicht, app starte nicht mehr. Passiert nichts mehr wenn ich im Startmenu auf den Button drücke"

Windows 10 Version Number: 
- [x] 1809

Device form factor:
- [X] Desktop

Where did you got the APP from?
- [X] Misc, got it from..."halt per developer mode installiert"

**Comment by Echolon** [comment]
Okay, he tried a reinstall, but now OMEMO doesn't work anymore he says.

Just FYI to check on this. was a jabber.de server (prosody)

**Comment by COM8** [comment]
Thanks for reporting!
Could you please update your issue to be 100% in English to keep it consistent?

* Windows don't move: All "old" pages are at the moment unmovable since the window now extends into the taskbar and they miss the "custom taskbar header". This should fix it selfe once more and more pages get updated to the new UI "style".
* I also noticed sometimes "enter to send" is bugged. Will look into it.
* Notifications look like they work for me even if the app runs not in focus. Pleas make sure he doesn't minimize it because than Windows suspends it and [push](https://github.com/UWPX/UWPX-Client/wiki/The-state-of-PUSH)  should take over.
* Yellow task bar icon if notification arrived: I allways hate this but sure I can make it an option.
* Every [release](https://github.com/UWPX/UWPX-Client/releases) includes a sideload build where you just have to run a powershell script to install it.
![grafik](https://user-images.githubusercontent.com/11741404/55781943-8c398c80-5aab-11e9-9a65-cb3709182b77.png)

I really need to know which version he is using to validate the bugs (go to `Settings` and scroll down).
![grafik](https://user-images.githubusercontent.com/11741404/55782129-f3574100-5aab-11e9-8656-7e7ed3bf5b1a.png)

**Comment by COM8** [comment]
> 
> 
> Okay, he tried a reinstall, but now OMEMO doesn't work anymore he says.
> 
> Just FYI to check on this. was a jabber.de server (prosody)

What is the status of OMEMO if he goes to `Settings` -> `Accounts` -> `ℹ` for the account -> `OMEMO`?
![grafik](https://user-images.githubusercontent.com/11741404/55782423-8bedc100-5aac-11e9-993f-761080806a26.png)

**Comment by Echolon** [comment]
HI,

now he could see it and said its:  0.15

OMEMO seems to work again and is enabled. Yesterday, there was a "failed to encrypt and send 1 omemo messages with: key_error" but he don't remember the status.

**Comment by COM8** [comment]
`key_error` usually means the DB instance is broken and loading the OMEMO keys for the own account failed.
Restarting the app should fix this.
This is directly related to #55

**Comment by COM8** [comment]
Looks to me like flashing the taskbar icon is not available to UWP apps, so changing the notification count is all I can do there.
![grafik](https://user-images.githubusercontent.com/11741404/55798385-16471c80-5acf-11e9-8756-842d1116fc86.png)

**Comment by Echolon** [comment]
Ok, would be fine I think

**Comment by COM8** [comment]
Looks like there is a bug with the title bar that prevents it from being scaled properly -> unable to drag window.

Reference: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/15657012-titlebar-extendviewintotitlebar-in-anniv-update-b

**Comment by Echolon** [comment]
Ah okay, yeah, if you could manage to build a workaround this is great.

Feel free to close this thread whenever you think its right.

**Comment by COM8** [comment]
Will keep it open till I got a fix for enter/shift-enter.
